generic-service:
  nameOverride: hmpps-probation-supervision-appointments-api
  productId: "HMPPS541" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-probation-supervision-appointments-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: probation-supervision-appointments-api-cert

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_DATASOURCE_URL: "jdbc:postgresql://${DB_HOST}/${DB_NAME}"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-probation-supervision-appointments-api:
      GRAPH_CLIENT_CLIENT_ID: GRAPH_CLIENT_ID
      GRAPH_CLIENT_CLIENT_SECRET: GRAPH_CLIENT_SECRET
      GRAPH_CLIENT_TENANT_ID: GRAPH_TENANT_ID
      CALENDAR_FROM_EMAIL: CALENDAR_FROM_EMAIL
      GOV_NOTIFY_API_KEY: NOTIFY_API_KEY
    rds-postgresql-instance-output:
      SPRING_DATASOURCE_USERNAME: "database_username"
      SPRING_DATASOURCE_PASSWORD: "database_password"
      DB_HOST: "rds_instance_endpoint"
      DB_NAME: "database_name"
    hmpps-probation-supervision-appointments-api-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-probation-supervision-appointments-api
