---
# Per environment values which override defaults in hmpps-probation-supervision-appointments-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: probation-supervision-appointments-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    GOVUK_NOTIFY_TEMPLATE_ID: "ff94ee5e-6799-441c-9c95-e777b3978297"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: probation-supervision-appointments-non-prod
