---
# Per environment values which override defaults in hmpps-probation-supervision-appointments-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: probation-supervision-appointments-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    GOVUK-NOTIFY_TEMPLATEIDS_ENGLISH-WITH-NAME-DATE: "7a3c8a69-30fb-4361-8a3b-125be59aeddf"
    GOVUK-NOTIFY_TEMPLATEIDS_ENGLISH-WITH-NAME-DATE-LOCATION: "4280ea18-1fc6-4356-80a7-d5f0ed8aac4a"
    GOVUK-NOTIFY_TEMPLATEIDS_WELSH-WITH-NAME-DATE: "887554f6-7765-4df3-a77d-aa833b22116e"
    GOVUK-NOTIFY_TEMPLATEIDS_WELSH-WITH-NAME-DATE-LOCATION: "b562b777-0931-4f9d-bd6f-ef99a23bdef9"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: probation-supervision-appointments-non-prod
