---
# Per environment values which override defaults in hmpps-probation-supervision-appointments-api/values.yaml

generic-service:
  replicaCount: 2
  ingress:
    host: probation-supervision-appointments-api.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    GOVUK_NOTIFY_TEMPLATE_ID: "tbc"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: probation-supervision-appointments
